Update push_image

diff --git a/script/push_image b/script/push_image
--- a/script/push_image
+++ b/script/push_image
@@ -10,13 +10,6 @@ KANIKO_CONFIG_PATH=${KANIKO_CONFIG_PATH:-"/kaniko/.docker"}
 # docker配置文件路径
 DOCKER_CONFIG_PATH=${DOCKER_CONFIG_PATH:-"$HOME/.docker"}
 
-# 检查源目录是否存在
-if [ -d "$KANIKO_CONFIG_PATH" ]; then
-    #  若存在则拷贝kaniko配置文件到docker配置文件目录
-    cp -r "$KANIKO_CONFIG_PATH" "$DOCKER_CONFIG_PATH"
-    echo "Copy $KANIKO_CONFIG_PATH to $DOCKER_CONFIG_PATH successfully."
-fi
-
 # 判断环境变量是否设置
 if [ -n "$LOCAL_IMAGE" ] && [ -n "$REMOTE_IMAGE" ]; then
 
@@ -28,6 +21,13 @@ if [ -n "$LOCAL_IMAGE" ] && [ -n "$REMOTE_IMAGE" ]; then
     TOTAL_WAIT=$((TOTAL_WAIT + SLEEP_TIME))
   done
 
+  # 检查kaniko配置目录是否存在
+  if [ -d "$KANIKO_CONFIG_PATH" ]; then
+      # 若存在则拷贝kaniko配置文件到docker配置文件目录
+      cp -r "$KANIKO_CONFIG_PATH" "$DOCKER_CONFIG_PATH"
+      echo "Copy $KANIKO_CONFIG_PATH to $DOCKER_CONFIG_PATH successfully."
+  fi
+
   # 判断镜像文件是否存在
   if [ -f "$LOCAL_IMAGE" ]; then
     # 检查 skopeo 命令是否存在
@@ -36,16 +36,17 @@ if [ -n "$LOCAL_IMAGE" ] && [ -n "$REMOTE_IMAGE" ]; then
         #skopeo copy docker-archive:$LOCAL_IMAGE docker://$REMOTE_IMAGE --tls-verify=false
         # --tls-verify=false已弃用 改为 --src-tls-verify=false --dest-tls-verify=false
         skopeo copy docker-archive:$LOCAL_IMAGE docker://$REMOTE_IMAGE --src-tls-verify=false --dest-tls-verify=false
+        if [ $? -eq 0 ]; then
+          echo "$REMOTE_IMAGE has been pushed to the remote repository successfully."
+        else
+          echo "$REMOTE_IMAGE Failed to be pushed to the remote repository."
+        fi
     else
-
         echo "The skopeo command is not installed. Install skopeo and try again."
     fi
-
   else
     echo "After waiting for ${TIME_OUT} seconds, no $LOCAL_IMAGE file is generated. Exit the program."
   fi
-
 #else
 #  echo "No environment variable is set for LOCAL_IMAGE or REMOTE_IMAGE."
-
 fi
